"""Adding user_clubs migration

Revision ID: a16ae976410b
Revises: ead7d275b27d
Create Date: 2021-07-20 11:40:18.512560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16ae976410b'
down_revision = 'ead7d275b27d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_clubs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'club_id')
    )
    op.drop_column('rsvps', 'id')
    op.alter_column('users', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('rsvps', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_table('user_clubs')
    # ### end Alembic commands ###
